default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: intro_to_rails_project_shah_development

test:
  <<: *default
  database: intro_to_rails_project_shah_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>